
name: backend

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: isbang/compose-action@v1.3.2
        with:
          compose-file: "./docker-compose.yml"

      - name: Install dependencies
        run: npm install

      - name: Wait for MySQL
        run: npm run wait-for-mysql

      - name: Run tests
        run: npm run test